
server:
  port: 8081
  servlet:
    context-path: /v1
spring:
  application:
    name: upp-backend
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://dev-microservices-db.labpetz.com.br:15432/postgres?currentSchema=upp}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:Ab0l1c40}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
      cache:
        #required - turn on L2 cache.
        use_second_level_cache: true
        #optional - turn on query cache.
        use_query_cache: true
        region:
          #required - classpath to cache region factory.
          factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    properties:
      hibernate:
        default_shema: upp
  flyway:
    baseline-on-migrate: true


